services:
  wrzesien550:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: loty_gui
    container_name: loty_wrzesien_550
    environment:
      - CONFIG_MODULE=config_sets.config_wrzesien_450
    volumes:
      - ./app:/app/app
    working_dir: /app
    command: bash /app/entrypoint.sh
  wrzesien750:
    image: loty_gui
    container_name: loty_wrzesien_750
    environment:
      - CONFIG_MODULE=config_sets.config_wrzesien_750
    volumes:
      - ./app:/app/app
    working_dir: /app
    command: bash /app/entrypoint.sh
  db:
    image: postgres:15
    container_name: flights_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
  
 