services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: loty_gui
    container_name: loty_web
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=flights
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash /app/entrypoint.sh
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: flights_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
